"""Type stubs for the native edgecrab._native module."""

from __future__ import annotations

from typing import Any, Optional

class Agent:
    """Autonomous AI agent — the primary entry point."""

    def __init__(
        self,
        model: str,
        *,
        max_iterations: Optional[int] = None,
        temperature: Optional[float] = None,
        streaming: Optional[bool] = None,
        session_id: Optional[str] = None,
        quiet_mode: Optional[bool] = None,
        instructions: Optional[str] = None,
        toolsets: Optional[list[str]] = None,
        disabled_toolsets: Optional[list[str]] = None,
        disabled_tools: Optional[list[str]] = None,
        skip_context_files: Optional[bool] = None,
        skip_memory: Optional[bool] = None,
    ) -> None: ...

    @staticmethod
    def from_config(config: Config) -> Agent: ...

    # Simple API
    def chat_sync(self, message: str) -> str: ...
    def run_sync(self, message: str) -> ConversationResult: ...
    def stream_sync(self, message: str) -> list[StreamEvent]: ...

    # Advanced API
    def run_conversation(
        self,
        message: str,
        *,
        system: Optional[str] = None,
        history: Optional[list[str]] = None,
    ) -> ConversationResult: ...
    def fork(self) -> Agent: ...
    def interrupt(self) -> None: ...
    def is_cancelled(self) -> bool: ...
    def new_session(self) -> None: ...

    # Session
    @property
    def session_id(self) -> Optional[str]: ...
    @property
    def history(self) -> list[dict[str, Any]]: ...
    @property
    def model(self) -> str: ...
    def export(self) -> dict[str, Any]: ...

    # Configuration
    def tool_names(self) -> list[str]: ...
    def toolset_summary(self) -> list[tuple[str, int]]: ...
    def list_sessions(self, limit: int = 20) -> list[SessionSummary]: ...
    def search_sessions(self, query: str, limit: int = 10) -> list[SessionSearchHit]: ...
    def set_reasoning_effort(self, effort: Optional[str] = None) -> None: ...
    def set_streaming(self, enabled: bool) -> None: ...
    def chat_in_cwd(self, message: str, cwd: str) -> str: ...
    def session_snapshot(self) -> dict[str, Any]: ...
    def compress(self) -> None: ...
    def set_model(self, model: str) -> None: ...
    def batch(self, messages: list[str]) -> list[Optional[str]]: ...

    @property
    def memory(self) -> MemoryManager: ...

class MemoryManager:
    """Programmatic access to the agent's persistent memory files."""

    def read(self, key: str = "memory") -> str: ...
    def write(self, key: str, value: str) -> None: ...
    def remove(self, key: str, old_content: str) -> bool: ...
    def entries(self, key: str = "memory") -> list[str]: ...

class Config:
    """EdgeCrab configuration."""

    @staticmethod
    def load() -> Config: ...
    @staticmethod
    def load_from(path: str) -> Config: ...
    @staticmethod
    def load_profile(name: str) -> Config: ...
    @staticmethod
    def default_config() -> Config: ...

    @property
    def default_model(self) -> str: ...
    @default_model.setter
    def default_model(self, value: str) -> None: ...
    @property
    def max_iterations(self) -> int: ...
    @max_iterations.setter
    def max_iterations(self, value: int) -> None: ...
    @property
    def temperature(self) -> Optional[float]: ...
    @temperature.setter
    def temperature(self, value: Optional[float]) -> None: ...
    def save(self) -> None: ...

class ConversationResult:
    """Result of a full conversation run."""

    response: str
    session_id: str
    api_calls: int
    interrupted: bool
    budget_exhausted: bool
    model: str
    input_tokens: int
    output_tokens: int
    total_cost: float

class StreamEvent:
    """A streaming event from the agent."""

    event_type: str
    data: str

class ModelCatalog:
    """Static catalog of available models."""

    def __init__(self) -> None: ...
    def provider_ids(self) -> list[str]: ...
    def models_for_provider(self, provider: str) -> list[tuple[str, str]]: ...
    def context_window(self, provider: str, model: str) -> Optional[int]: ...
    def pricing(self, provider: str, model: str) -> Optional[tuple[float, float]]: ...
    def flat_catalog(self) -> list[tuple[str, str, str]]: ...
    def default_model_for(self, provider: str) -> Optional[str]: ...
    def estimate_cost(
        self, provider: str, model: str, input_tokens: int, output_tokens: int
    ) -> Optional[tuple[float, float, float]]: ...

class SessionSummary:
    """Summary of a stored session."""

    session_id: str
    source: str
    model: Optional[str]
    started_at: float
    message_count: int
    title: Optional[str]

class SessionSearchHit:
    """A search result from session search."""

    session_id: str
    role: str
    snippet: str
    score: float

class Session:
    """Standalone session store access."""

    def __init__(self, path: Optional[str] = None) -> None: ...
    def list_sessions(self, limit: int = 20) -> list[SessionSummary]: ...
    def search_sessions(self, query: str, limit: int = 10) -> list[SessionSearchHit]: ...
    def get_messages(self, session_id: str) -> list[dict[str, Any]]: ...
    def delete_session(self, session_id: str) -> None: ...
    def rename_session(self, session_id: str, title: str) -> None: ...
    def prune_sessions(
        self, older_than_days: int, source: Optional[str] = None
    ) -> int: ...
    def stats(self) -> SessionStats: ...

class SessionStats:
    """Aggregate session store statistics."""

    total_sessions: int
    total_messages: int
    db_size_bytes: int

def edgecrab_home() -> str: ...
def ensure_edgecrab_home() -> str: ...
