/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * The EdgeCrab Agent — build and interact with autonomous AI agents.
 *
 * ```js
 * const { Agent } = require('edgecrab');
 * const agent = new Agent({ model: 'anthropic/claude-sonnet-4' });
 * const reply = await agent.chat('Hello!');
 * ```
 */
export declare class Agent {
  /** Create a new Agent with the given options. */
  constructor(options?: AgentOptions | undefined | null)
  /** Create an Agent from a loaded Config object. */
  static fromConfig(config: JsConfig): Agent
  /** Send a message and get the response. Returns a Promise<string>. */
  chat(message: string): Promise<string>
  /** Send a message in a specific working directory. Returns a Promise<string>. */
  chatInCwd(message: string, cwd: string): Promise<string>
  /** Run a full conversation and get detailed results. Returns Promise<ConversationResult>. */
  run(message: string): Promise<JsConversationResult>
  /** Run a conversation with optional system prompt and history. */
  runConversation(message: string, system?: string | undefined | null, history?: Array<string> | undefined | null): Promise<JsConversationResult>
  /** Stream events from the agent. Returns Promise<StreamEvent[]>. */
  stream(message: string): Promise<Array<JsStreamEvent>>
  /** Interrupt the current agent run. */
  interrupt(): void
  /** Check if the agent has been cancelled. */
  get isCancelled(): boolean
  /** Start a new session (reset conversation). */
  newSession(): Promise<void>
  /** Get the current model name. */
  get model(): Promise<string>
  /** Get the current session ID, if any. */
  get sessionId(): Promise<string | null>
  /** Get the conversation history as an array of message objects. */
  getHistory(): Promise<Array<any>>
  /** Fork the agent into an isolated copy for parallel/background work. */
  fork(): Promise<Agent>
  /** Export the current session (snapshot + full message history). */
  export(): Promise<any>
  /** List available tool names. */
  toolNames(): Promise<Array<string>>
  /** Get a summary of toolsets and their tool counts. */
  toolsetSummary(): Promise<Array<Array<any>>>
  /** List recent sessions. */
  listSessions(limit?: number | undefined | null): Array<JsSessionSummary>
  /** Search sessions by text. */
  searchSessions(query: string, limit?: number | undefined | null): Array<JsSessionSearchHit>
  /** Set the reasoning effort level. */
  setReasoningEffort(effort?: string | undefined | null): Promise<void>
  /** Enable or disable streaming mode. */
  setStreaming(enabled: boolean): Promise<void>
  /** Get a snapshot of the current session state. */
  sessionSnapshot(): Promise<any>
  /** Force context compression — summarise conversation history to free context window. */
  compress(): Promise<void>
  /** Hot-swap the model at runtime. Takes "provider/model" string. */
  setModel(model: string): Promise<void>
  /**
   * Run multiple prompts in parallel, returning results in order.
   * Failed items are returned as null.
   */
  batch(messages: Array<string>): Promise<Array<string | undefined | null>>
  /** Get a MemoryManager for reading/writing agent memory. */
  get memory(): JsMemoryManager
}
export type JsAgent = Agent

/** EdgeCrab configuration. */
export declare class Config {
  /** Load configuration from the default location. */
  static load(): Config
  /** Load configuration from a specific path. */
  static loadFrom(path: string): Config
  /** Load configuration for a named profile. */
  static loadProfile(name: string): Config
  /** Create a default configuration. */
  static defaultConfig(): Config
  /** Get the default model string. */
  get defaultModel(): string
  /** Set the default model string. */
  set defaultModel(model: string)
  /** Get the max iterations setting. */
  get maxIterations(): number
  /** Set the max iterations. */
  set maxIterations(n: number)
  /** Get the temperature setting. */
  get temperature(): number | null
  /** Set the temperature. */
  set temperature(t: number | undefined | null)
  /** Save the configuration to disk (~/.edgecrab/config.yaml). */
  save(): void
}
export type JsConfig = Config

/**
 * Programmatic access to the agent's persistent memory files.
 *
 * ```js
 * const mem = agent.memory;
 * const content = await mem.read('memory');
 * await mem.write('memory', 'Important fact');
 * ```
 */
export declare class MemoryManager {
  /**
   * Read the contents of a memory file.
   * key: "memory" (MEMORY.md) or "user" (USER.md).
   */
  read(key?: string | undefined | null): Promise<string>
  /** Write (append) a new entry to a memory file. */
  write(key: string, value: string): Promise<void>
  /**
   * Remove an entry by substring match.
   * Returns true if an entry was removed.
   */
  remove(key: string, oldContent: string): Promise<boolean>
  /** List all entries from a memory file as an array of strings. */
  entries(key?: string | undefined | null): Promise<Array<string>>
}
export type JsMemoryManager = MemoryManager

/** Model catalog — query available models and pricing. */
export declare class ModelCatalog {
  /** Create a new ModelCatalog instance. */
  constructor()
  /** List all provider IDs. */
  providerIds(): Array<string>
  /** List model IDs for a given provider. Returns array of [model_id, display_name]. */
  modelsForProvider(provider: string): Array<Array<string>>
  /** Get the context window size for a model. */
  contextWindow(provider: string, model: string): number | null
  /** Get pricing for a provider/model pair. Returns [input_cost, output_cost] per 1M tokens. */
  pricing(provider: string, model: string): Array<number> | null
  /** Flat list of all models: [[provider, model_id, display_name], ...]. */
  flatCatalog(): Array<Array<string>>
  /** Get the default model for a provider. */
  defaultModelFor(provider: string): string | null
  /**
   * Estimate cost (USD) for a given token count.
   * Returns [input_cost, output_cost, total_cost] or null.
   */
  estimateCost(provider: string, model: string, inputTokens: number, outputTokens: number): Array<number> | null
}
export type JsModelCatalog = ModelCatalog

/** Standalone session store access — query sessions without creating an Agent. */
export declare class Session {
  /** Open the session database. If path is not given, opens the default DB. */
  constructor(path?: string | undefined | null)
  /** List recent sessions. */
  listSessions(limit?: number | undefined | null): Array<JsSessionSummary>
  /** Search sessions by text. */
  searchSessions(query: string, limit?: number | undefined | null): Array<JsSessionSearchHit>
  /** Get all messages for a session. */
  getMessages(sessionId: string): Array<any>
  /** Delete a session by ID. */
  deleteSession(sessionId: string): void
  /** Rename a session (set its title). */
  renameSession(sessionId: string, title: string): void
  /**
   * Prune sessions older than the given number of days.
   * Optionally filter by source. Returns number of deleted sessions.
   */
  pruneSessions(olderThanDays: number, source?: string | undefined | null): number
  /**
   * Get aggregate statistics about the session store.
   * Returns { total_sessions, total_messages, db_size_bytes }.
   */
  stats(): JsSessionStats
}
export type JsSession = Session

/** Options for creating a new Agent. */
export interface AgentOptions {
  /** Model identifier (e.g. "anthropic/claude-sonnet-4"). */
  model?: string
  /** Maximum tool-use iterations per turn. */
  maxIterations?: number
  /** Sampling temperature. */
  temperature?: number
  /** Enable token streaming. */
  streaming?: boolean
  /** Resume a specific session. */
  sessionId?: string
  /** Suppress internal logging. */
  quietMode?: boolean
  /** Custom instructions appended to system prompt. */
  instructions?: string
  /** Enable only these toolsets. */
  toolsets?: Array<string>
  /** Disable these toolsets. */
  disabledToolsets?: Array<string>
  /** Disable specific tools by name. */
  disabledTools?: Array<string>
  /** Skip loading workspace context files like AGENTS.md. */
  skipContextFiles?: boolean
  /** Skip loading persistent memory and user profile sections. */
  skipMemory?: boolean
}

/**
 * Get the EdgeCrab home directory path (usually ~/.edgecrab).
 *
 * This is exported for the Node.js public API and is referenced from JS/TS,
 * which Rust's dead-code analysis for test targets cannot see.
 */
export declare function edgecrabHome(): string

/**
 * Ensure the EdgeCrab home directory exists, creating it if needed.
 *
 * This is exported for the Node.js public API and is referenced from JS/TS,
 * which Rust's dead-code analysis for test targets cannot see.
 */
export declare function ensureEdgecrabHome(): string

/** Result of a full conversation run. */
export interface JsConversationResult {
  /** The final assistant response text. */
  response: string
  /** Session ID used for this conversation. */
  sessionId: string
  /** Number of API calls made. */
  apiCalls: number
  /** Whether the agent was interrupted. */
  interrupted: boolean
  /** Whether the iteration budget was exhausted. */
  budgetExhausted: boolean
  /** Model used. */
  model: string
  /** Total input tokens. */
  inputTokens: number
  /** Total output tokens. */
  outputTokens: number
  /** Total cost in USD. */
  totalCost: number
}

/** Session search result. */
export interface JsSessionSearchHit {
  /** Session ID where the match was found. */
  sessionId: string
  /** Role of the matching message. */
  role: string
  /** Matching text snippet. */
  snippet: string
  /** Relevance score. */
  score: number
}

/** Session statistics. */
export interface JsSessionStats {
  /** Total number of sessions. */
  totalSessions: number
  /** Total number of messages across all sessions. */
  totalMessages: number
  /** Database size in bytes. */
  dbSizeBytes: number
}

/** Session summary. */
export interface JsSessionSummary {
  /** Unique session identifier. */
  sessionId: string
  /** Session source. */
  source: string
  /** Model used (if known). */
  model?: string
  /** Start timestamp (Unix seconds). */
  startedAt: number
  /** Number of messages. */
  messageCount: number
  /** Session title (if set). */
  title?: string
}

/** A streaming event from the agent. */
export interface JsStreamEvent {
  /** Event type: "token", "reasoning", "tool_exec", "tool_result", "done", "error", "info" */
  eventType: string
  /** Event data (text content, tool name, error message, etc.) */
  data: string
}
